const START_GAME = "START_GAME";
const QUIT_GAME = "QUIT_GAME";

const MULLIGAN_PENDING = "MULLIGAN_PENDING";
const MULLIGAN_COMPLETED = "MULLIGAN_COMPLETED";
const MULLIGAN_REPLACE = "MULLIGAN_REPLACE";

export {
  START_GAME,
  QUIT_GAME,
  MULLIGAN_PENDING,
  MULLIGAN_COMPLETED,
  MULLIGAN_REPLACE
};
