const GAME_START = "GAME_START";
const MULLIGAN_PENDING = "MULLIGAN_PENDING";
const MULLIGAN_COMPLETED = "MULLIGAN_COMPLETED";
const MULLIGAN_REPLACE = "MULLIGAN_REPLACE";
const QUIT_GAME = "QUIT_GAME";

export {
  GAME_START,
  MULLIGAN_PENDING,
  MULLIGAN_COMPLETED,
  MULLIGAN_REPLACE,
  QUIT_GAME
};
